# Имя устройства в меню Bluetooth
CONFIG_BT_DEVICE_NAME="Trackball"

# Включаем Bluetooth-стек
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# ВАЖНО: Строка CLEAR_BONDS удалена, чтобы устройство сохраняло сопряжение!

# Поддержка работы по USB (на случай тестов по проводу)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_VID=0x1d50
CONFIG_USB_DEVICE_PID=0x616e
CONFIG_USB_DEVICE_MANUFACTURER="ZMK"
CONFIG_USB_DEVICE_PRODUCT="Trackball"

# Логирование (помогает при отладке через USB-ардуино монитор порта)
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Активация подсистемы мыши и SPI
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PAW3395=y